### ISSUE TITLE
Time difference dummynet/TSProxy/WebPageTest

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/tsproxy#10]
Hey Pat, 
one question about the expected outcome. When I test locally in Chrome setting TSProxy with "cable" connection (<code>python tsproxy.py --rtt=28 --inkbps=5000 --outkbps=1000</code> and testing https://en.wikipedia.org/wiki/Barack_Obama the finish time (in the Chrome bar) is usually something like 17s (and the load time) and testing the same in WebPageTest get fully loaded like 5-6 seconds. Is that the difference we should expect? Or is it stupid to compare?

Best
Peter

**Comment by pmeenan** [comment]
All things being equal and on a fast enough machine I'd usually expect tsproxy to be slightly faster, not that much slower (since it doesn't shape slow start).  That assumes the page load isn't otherwise CPU constrained and it is running fast enough to be able to tick at 1ms in tsproxy (which is the dummynet tick interval).

Hard to say exactly what the difference is coming from but traces/timelines of both might help.

**Comment by soulgalore** [comment]
I was also of the impression that tsproxy would be a little bit faster, lets see if I can find a way to compare on the same machine and provide logs.

**Comment by pmeenan** [comment]
Ignore the WPT timings and the waterfalls because clearly they are wrong but the visual metrics and the w3c user timing metrics from these should be good to compare.

Here are 2 sets of tests I ran back-to-back on the same machine.  One with [dummynet](https://www.webpagetest.org/results.php?test=161024_H4_9b98f4934e43b59a24ae5bccc7c25d45) cable profile and one with [tsproxy](https://www.webpagetest.org/results.php?test=161024_H4_9b98f4934e43b59a24ae5bccc7c25d45) with the same profile.

#Dummynet:
SpeedIndex: ~2500
Start Render: ~2450
mwLoadStart: ~2145
mwLoadEnd: ~3100

#tsproxy
SpeedIndex: ~1450
Start Render: ~1400
mwLoadStart (user timing mark): ~1200-~2400 (bimodal)
mwLoadEnd: ~4000

For the most part tsproxy is a bit faster.  I'll take a look to see if I can get the slow start emulation back in place which would help slow it down a bit (particularly early on where start render is) and I'm also experimenting with making it a little less of a CPU hog in case it is running on a lower-end VM (right now it runs in a tight polling loop of 1ms but I can change that to sleep longer if the time for delivering the next packet is still a while away).

**Comment by soulgalore** [comment]
thanks Pat, something on my local then. The most difference is with fully loaded seems like images are queued up. will try to compare with tc to see if I see the same thing there so I'm comparing apples with almost apples :)

**Comment by JCofman** [comment]
I had the same issues when throttling the connection speed as @soulgalore . While using tsproxy ```python tsproxy.py --rtt 300 --inkbps 1600 --outkbps 768``` testing  https://www.inovex.de/de/ resulted in a finish time of 1.679 minutes while throttling the connection with chrome or using WebPageTest resulted in finish time of roughly 18 seconds.

**Comment by soulgalore** [comment]
I wonder if it could be a OS thing, that it works fine on Windows but not Linux or if we are using wrong somehow?

**Comment by pmeenan** [comment]
It looks like my recent changes caused [issues](https://codereview.chromium.org/2516973005/) on Linux/OSX systems.  I'm working on fixing it right now.

**Comment by soulgalore** [comment]
cool, I'm pretty sure I had the same behavior before that fix though. But as always, I'm not 100% sure :)

**Comment by pmeenan** [comment]
Hmm.  Can you try with the latest?  I fixed the issues that were causing Chrome issues on Mac/Linux but I think something else may be going on.

If you run with -vvvv it will dump a bunch of debug info.

Any chance you are using a service of some kind that automatically adjusts image quality based on connection speed?  If so, those will detect tsproxy as a fast connection since it doesn't operate at the packet level.  I just loaded the page locally in my linux VM and it took well over 18 seconds to load and it looked like the time was because of the background image and the whole time was a flood of data coming in.

**Comment by soulgalore** [comment]
I did a quick test with the latest version, testing against https://en.wikipedia.org/wiki/Barack_Obama using --rtt 300 --inkbps 1600 --outkbps 768 and on Chrome Mac OS X and I got the same behavior as before (we don't adjust image quality), load time of 119 s. I'll need to run the proxy standalone to get the logs, will do that later tonight.

**Comment by soulgalore** [comment]
I was wrong, this works fine now if I run tsproxy standalone and configure Chrome to use it. In my case where I use Selenium to start Chrome, there's something there that makes it so slow.
